spring:
  application:
    name: cloud-jifen #服务名称，必须，保证唯一
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #指定nacos-server的Nginx地址
        username: nacos
        password: nacos
    # sentinel配置
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8888
      web-context-unify: false # 可以根据不同的URL进行链路限流
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sleuth:
      sampler:
        # 限速器，每秒采集10个请求，防止大并发过载。推荐
        rate: 10
# 积分服务的端口号
server:
  port: ${port:7001}
